export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_USER = 'GET_USER';
export const GET_COURSES = 'GET_COURSES';
export const CREATE_COURSE = 'CREATE_COURSE';
export const GET_COURSE = 'GET_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const ERRORS = 'ERRORS';
export const REMOVE_ERRORS = 'REMOVE_ERRORS';

export const GET_COURSE_GRADES = 'GET_COURSE_GRADES';
export const GET_COURSE_ASSIGN_GRADES = 'GET_COURSE_ASSIGN_GRADES';
